# Generated by Django 4.0 on 2023-10-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
